while True:
  from time import sleep
  phone = input('enter phone number ex. 393287654265 ')
  print('creatintg list...')
  sleep(2)
  print()
  print()
  print('intext ' + phone)
  print('intitle ' + phone)
  print('inurl ' + phone)
  print('~name * ' + phone)
  print('filetype:log intext: ' + phone)
  print('filetype:db intext: ' + phone)
  print('filetype:env intext: ' + phone)
  print('filetype:pdf intext: ' + phone)
  print('email * ' + phone)
  print('mail * ' + phone)
  print('gmail * ' + phone)
  print('@facebook ' + phone)
  print('@linkedin ' + phone)
  print('@instagram ' + phone)
  print('@snapchat ' + phone)
  print('intext + ' + phone)
  print('intitle +' + phone)
  print('inurl +' + phone)
  print('~name * +' + phone)
  print('filetype:log intext: +' + phone)
  print('filetype:db intext: +' + phone)
  print('filetype:env intext: +' + phone)
  print('filetype:pdf intext: +' + phone)
  print('email * +' + phone)
  print('mail * +' + phone)
  print('gmail * +' + phone)
  print('@facebook +' + phone)
  print('@linkedin +' + phone)
  print('@instagram +' + phone)
  print('@snapchat +' + phone)
  print('intext ' + phone[:2] + ' ' + phone[2:])
  print('intitle ' + phone[:2] + ' ' + phone[2:])
  print('inurl ' + phone[:2] + ' ' + phone[2:])
  print('~name * ' + phone[:2] + ' ' + phone[2:])
  print('filetype:log intext: ' + phone[:2] + ' ' + phone[2:])
  print('filetype:db intext: ' + phone[:2] + ' ' + phone[2:])
  print('filetype:env intext: ' + phone[:2] + ' ' + phone[2:])
  print('filetype:pdf intext: ' + phone[:2] + ' ' + phone[2:])
  print('email * ' + phone[:2] + ' ' + phone[2:])
  print('mail * ' + phone[:2] + ' ' + phone[2:])
  print('gmail * ' + phone[:2] + ' ' + phone[2:])
  print('@facebook ' + phone[:2] + ' ' + phone[2:])
  print('@linkedin ' + phone[:2] + ' ' + phone[2:])
  print('@instagram ' + phone[:2] + ' ' + phone[2:])
  print('@snapchat ' + phone[:2] + ' ' + phone[2:])
  print('intext +' + phone[:2] + ' ' + phone[2:])
  print('intitle +' + phone[:2] + ' ' + phone[2:])
  print('inurl +' + phone[:2] + ' ' + phone[2:])
  print('~name * +' + phone[:2] + ' ' + phone[2:])
  print('filetype:log intext:+ ' + phone[:2] + ' ' + phone[2:])
  print('filetype:db intext:+ ' + phone[:2] + ' ' + phone[2:])
  print('filetype:env intext:+' + phone[:2] + ' ' + phone[2:])
  print('filetype:pdf intext: + ' + phone[:2] + ' ' + phone[2:])
  print('email * +' + phone[:2] + ' ' + phone[2:])
  print('mail * +' + phone[:2] + ' ' + phone[2:])
  print('gmail * +' + phone[:2] + ' ' + phone[2:])
  print('@facebook +' + phone[:2] + ' ' + phone[2:])
  print('@linkedin +' + phone[:2] + ' ' + phone[2:])
  print('@instagram +' + phone[:2] + ' ' + phone[2:])
  print('@snapchat +' + phone[:2] + ' ' + phone[2:])
  print('intext ' + phone[2:])
  print('intitle ' + phone[2:])
  print('inurl ' + phone[2:])
  print('~name * ' + phone[2:])
  print('filetype:log intext: ' + phone[2:])
  print('filetype:db intext: ' + phone[2:])
  print('filetype:env intext: ' + phone[2:])
  print('filetype:pdf intext: ' + phone[2:])
  print('email * ' + phone[2:])
  print('mail * ' + phone[2:])
  print('gmail * ' + phone[2:])
  print('@facebook ' + phone[2:])
  print('@linkedin ' + phone[2:])
  print('@instagram ' + phone[2:])
  print('@snapchat ' + phone[2:])
  print('intext:' + phone[2:])
  print('intitle:' + phone[2:])
  print('inurl:' + phone[2:])
  print('~name * ' + phone[2:])
  print('filetype:log intext:' + phone[2:])
  print('filetype:db intext:' + phone[2:])
  print('filetype:env intext:' + phone[2:])
  print('filetype:pdf intext:' + phone[2:])
  print('email * ' + phone[2:])
  print('mail * ' + phone[2:])
  print('gmail * ' + phone[2:])
  print('@facebook' + phone[2:])
  print('@linkedin' + phone[2:])
  print('@instagram' + phone[2:])
  print('@snapchat ' + phone[2:])
  print('~password intext:' + phone)
  print('~password intext:' + '+' + phone[:2] + phone[2:])
  print('~password intext:' + phone[:2] + ' ' + phone[2:])
  print('~password intext:' + phone[2:])
  print('~password intext:+' + phone)
  print()
  print('OTHER COMPLEXT DORKS')
  print('-' * 25)
  print('(intext | intitle | inurl): ' + phone)
  print('(intext | intitle | inurl): ' + '+' + phone[:2] + phone[2:])
  print('(intext | intitle | inurl): ' + phone[:2] + ' ' + phone[2:])
  print('(intext | intitle | inurl): ' + phone[2:])
  print('(intext | intitle | inurl): +' + phone)
  print('@(facebook | snapchat | instagram | linkedin) ' + phone)
  print('@(facebook | snapchat | instagram | linkedin) ' + '+' + phone[:2] + phone[2:])
  print('@(facebook | snapchat | instagram | linkedin) ' + phone[:2] + ' ' + phone[2:])
  print('@(facebook | snapchat | instagram | linkedin) ' + phone[2:]) 
  print('@(facebook | snapchat | instagram | linkedin) +' + phone)
  print('intext: (' + phone + ' | ' + phone[:2] + ' ' + phone[2:] + ' | ' + phone[2:] + ' | ' + '+' + phone[:2] + phone[2:] + ')')
  print('filetype:env (intext | intitle | inurl): (' + phone + ' | ' + phone[:2] + ' ' + phone[2:] + ' | ' + phone[2:] + ' | ' + '+' + phone[:2] + phone[2:] + ')')
  print()
  print('_' * 60)
  print()
